https://www.tensorflow.org/tutorials/quickstart/beginner

In [1]:
import tensorflow as tf
print(f'Tensor Flow version: {tf.__version__}')


Tensor Flow version: 2.15.0


Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


Building a Machine Learning model

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [12]:
# sample
predicts = model(x_train[:1]).numpy()
model(x_train[:1]).numpy()

array([[-0.67710274, -0.62777925,  0.0700049 , -0.32649222, -0.16516738,
         0.3997078 , -0.01323566,  0.68039924,  0.61871773,  0.05273482]],
      dtype=float32)

In [11]:
tf.nn.softmax(predicts).numpy()

array([[0.04599245, 0.04831783, 0.0970848 , 0.06530625, 0.07673918,
        0.13500176, 0.08933062, 0.1787484 , 0.16805607, 0.09542254]],
      dtype=float32)

Loss Function

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and Evaluate

In [17]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


1875/1875 [==============================] - 3s 1ms/step - loss: 0.3010 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1468 - accuracy: 0.9564
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1088 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0894 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0752 - accuracy: 0.9768


In [18]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0742 - accuracy: 0.9775 - 346ms/epoch - 1ms/step


[0.07418476045131683, 0.9775000214576721]

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2196305e-07, 3.5997033e-08, 6.9094472e-07, 4.2730686e-04,
        8.3926269e-12, 1.4579035e-07, 1.4143576e-13, 9.9957126e-01,
        2.6170909e-07, 2.2799567e-07],
       [1.2560201e-07, 1.1214565e-04, 9.9986517e-01, 2.0264908e-05,
        1.4605221e-16, 2.1159190e-06, 5.7812338e-10, 2.3875894e-14,
        1.4320185e-07, 1.9643082e-13],
       [1.1948453e-07, 9.9926561e-01, 4.8756214e-05, 1.9641438e-05,
        4.5951467e-05, 2.0751795e-06, 4.2094766e-06, 5.0094840e-04,
        1.0991323e-04, 2.8292482e-06],
       [9.9997020e-01, 6.3588368e-10, 1.4789688e-05, 2.5252126e-08,
        1.4377750e-08, 1.6971902e-06, 9.8899100e-06, 1.7323734e-06,
        6.2625027e-08, 1.6083790e-06],
       [4.8778552e-06, 2.5264657e-09, 7.7414797e-06, 2.7363865e-07,
        9.9561453e-01, 6.1572834e-08, 2.8565162e-06, 8.0356731e-05,
        6.9062880e-06, 4.2824377e-03]], dtype=float32)>